---
title: "final_project_yg2625"
author: "yue gu"
date: "12/10/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(HH)
library(leaps)
```


## Stepwise

```{r}


##d = death_data
##d[is.na(d)] = 0

fit = lm(target_death_rate ~ ., data = death_data)

step(fit, data = death_data, direction = "both" )

## backward
summary(lm(formula = target_death_rate ~ incidence_rate + med_income + 
    poverty_percent + median_age_male + percent_married + pct_hs18_24 + 
    pct_hs25_over + pct_bach_deg25_over + pct_employed16_over + 
    pct_unemployed16_over + pct_private_coverage + pct_emp_priv_coverage + 
    pct_white + pct_black + pct_married_households + birth_rate + 
    race_other + region_w + region_sw + region_me + region_se + 
    sex_ratio + pct_aging, data = death_data))

## forward
summary(lm(formula = target_death_rate ~ incidence_rate + med_income + 
    pop_est2015 + poverty_percent + study_per_cap + median_age + 
    median_age_male + median_age_female + avg_household_size + 
    percent_married + pct_no_hs18_24 + pct_hs18_24 + pct_bach_deg18_24 + 
    pct_hs25_over + pct_bach_deg25_over + pct_employed16_over + 
    pct_unemployed16_over + pct_private_coverage + pct_private_coverage_alone + 
    pct_emp_priv_coverage + pct_public_coverage + pct_public_coverage_alone + 
    pct_white + pct_black + pct_married_households + birth_rate + 
    race_other + region_w + region_sw + region_me + region_se + 
    sex_ratio + pct_aging, data = death_data))

## both
summary(lm(formula = target_death_rate ~ incidence_rate + med_income + 
    poverty_percent + median_age_male + percent_married + pct_hs18_24 + 
    pct_hs25_over + pct_bach_deg25_over + pct_employed16_over + 
    pct_unemployed16_over + pct_private_coverage + pct_emp_priv_coverage + 
    pct_white + pct_black + pct_married_households + birth_rate + 
    race_other + region_w + region_sw + region_me + region_se + 
    sex_ratio + pct_aging, data = death_data))
```


## VIF
```{r}
death_data_1 = death_data %>%
  dplyr::select(-c(med_income, pct_private_coverage))

fit_full_1 = lm(target_death_rate ~., data = death_data_1)

vif(fit_full_1)

## Delete varibles with high vif
death_data_2 = death_data_1 %>%
  dplyr::select(-c(pct_white, median_age, percent_married, pct_public_coverage, median_age_male))

fit_full_2 = lm(target_death_rate ~., data = death_data_2)

vif(fit_full_2)



## Delete variables with vif > 5, keep poverty_percent since it provided more information
death_data_3 = death_data_2 %>%
  dplyr::select(-c(pct_emp_priv_coverage, pct_bach_deg25_over ))
  

fit_full_3 = lm(target_death_rate ~., data = death_data_3)

vif(fit_full_3)

summary(fit_full_3)

```


