---
title: "lasso_model"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(glmnet)
library(leaps)
```

```{r load_data}
death_data_full = read_csv("data/Cancer_Registry.csv") %>%
    janitor::clean_names() %>%
    mutate(median_age = ifelse(median_age >60, NA, median_age)) %>%
    separate(geography, into = c("county", "state"), sep = ", ") %>%
    mutate(study_per_cap = ifelse(study_per_cap == 0,0,1)) %>%
    mutate(race_other = pct_other_race + pct_asian) %>%
    mutate(state = ifelse(state == "District of Columbia", "DC", state.abb[match(state, state.name)])) %>% 
    mutate(region_w = ifelse(state == "WA" | state == "MT" | state == "ID" | state == "OR" | state == "WY" | state == "NV" | state == "UT" | state == "CO" | state == "CA", 1, 0),
           region_sw = ifelse(state == "AZ" | state == "NM" | state == "TX" | state == "OK", 1, 0),
           region_me = ifelse(state == "ND" | state == "SD" | state == "NE" | state == "KS" | state == "MN" | state == "IA" | state == "MO" | state == "WI" | state == "IL" | state == "MI" | state == "IN" | state == "OH", 1, 0),
           region_se = ifelse(state == "AR" | state == "LA" | state == "MS" | state == "AL" | state == "GA" | state == "FL" | state == "SC" | state == "NC" | state == "TN" | state == "KY" | state == "VA" | state == "WV" | state == "MD" | state == "DC" , 1, 0)) %>% 
   unite(geography,c(county, state), sep = ", ")
    

sex_data = read_csv("./data/SEX01.csv") %>% 
  dplyr::select(Areaname,SEX255209D) %>% 
  separate(Areaname, c("county","state"), sep = ", ") %>% 
  na.omit() %>% 
  mutate(county = paste(county,"County", sep = " "),
         sex_ratio = SEX255209D) %>% 
  unite(geography,c(county, state), sep = ", ") %>% 
  dplyr::select(geography,sex_ratio)

age_data=read_csv("./data/AGE04.csv") %>% 
  dplyr::select(Areaname,AGE775208D) %>% 
  separate(Areaname, c("county","state"), sep = ", ") %>% 
  na.omit() %>% 
  mutate(county = paste(county,"County", sep = " "),
         pct_aging = AGE775208D) %>% 
  unite(geography,c(county, state), sep = ", ") %>% 
  dplyr::select(geography,pct_aging)

cancer_1 = left_join(death_data_full,sex_data,by = "geography")
death_data_full = left_join(cancer_1,age_data,by = "geography") 

death_data_full = death_data_full %>% 
  separate(geography, c("county","state"), sep = ", ")

death_data =
  death_data_full %>%
  janitor::clean_names() %>%
  dplyr::select(-c(avg_ann_count,avg_deaths_per_year, pct_some_col18_24, binned_inc, county, pct_asian, pct_other_race,state)) %>% 
  mutate(sex_ratio = replace_na(sex_ratio,50.2), pct_aging = replace_na(pct_aging,15.58), pct_private_coverage_alone = replace_na(pct_private_coverage_alone,48.48), pct_employed16_over = replace_na(pct_employed16_over,48.48), median_age = replace_na(median_age,40.82))
```

```{r lasso, fig.width=10, fig.height=30}
d = death_data

cancer_x = d %>%
  dplyr::select(- target_death_rate)

predictor = as.matrix(cancer_x)

target = as.matrix(d$target_death_rate)

grid <- 10^seq(-0.1,0, length = 30)

train<-sample(1:3059,2753)

test<-(-train)

cv.out<-cv.glmnet(predictor[train,],target[train])
plot(cv.out)

best.lambda<-cv.out$lambda.min

lasso <- cv.glmnet(predictor, target, standardize = TRUE, lambda = grid)

best.lambda<-cv.out$lambda.min

plot(lasso$glmnet.fit, "lambda", label=TRUE)

colnames(predictor)
```


```{r linear}
fit = lm(target_death_rate ~ pct_bach_deg25_over + incidence_rate + region_w + pct_hs18_24 + pct_hs25_over + pct_unemployed16_over + poverty_percent + region_se + pct_married_households + sex_ratio + race_other + pct_private_coverage, data = d)

summary(fit)
```

```{r cv}
set.seed(1)
data_train = trainControl(method = "cv", number = 10)

vif_reg = lm(target_death_rate ~ incidence_rate +
                      median_age_female+
                      poverty_percent+
                      avg_household_size + percent_married +
                      pct_employed16_over+
                      pct_bach_deg18_24 + pct_hs25_over +
                      pct_unemployed16_over + 
                      pct_public_coverage_alone + 
                      pct_black + pct_married_households + birth_rate +
                      race_other + region_w + region_sw + region_me +
                      region_se + sex_ratio+pct_aging, data =
                      d)

lasso_reg = lm(target_death_rate ~ pct_bach_deg25_over + incidence_rate +
region_w + pct_hs18_24 + pct_hs25_over + pct_unemployed16_over + poverty_percent + region_se +
 pct_married_households + sex_ratio + race_other + pct_private_coverage, data =
                      d)
  
step_reg = lm(target_death_rate ~ incidence_rate + med_income + poverty_percent  + median_age_male + percent_married +
pct_hs18_24 + pct_hs25_over + pct_bach_deg25_over + pct_employed16_over + pct_unemployed16_over  +
pct_private_coverage + pct_emp_priv_coverage + pct_white + pct_black + pct_married_households +
birth_rate  + race_other + region_w + region_sw + region_me + region_se + sex_ratio + pct_aging, data =
                      d)

cv_df =
  crossv_kfold(death_data, k=10) %>% 
  mutate(train = map(train, as_tibble),
         test = map(test, as_tibble))

cv_df = 
  cv_df %>% 
  mutate(step_mod = map(train, ~step_reg),
         lasso_mod = map(train, ~lasso_reg),
         vif_mod = map(train, ~vif_reg)) %>% 
  mutate(rmse_step    = map2_dbl(step_mod, test, ~rmse(model = .x, data = .y)),
         rmse_lasso = map2_dbl(lasso_mod, test, ~rmse(model = .x, data = .y)),
         rmse_vif = map2_dbl(vif_mod, test, ~rmse(model = .x, data = .y)))
  
cv_df %>% 
  dplyr::select(starts_with("rmse")) %>% 
  gather(key = model, value = rmse) %>% 
  mutate(model = str_replace(model, "rmse_", ""),
         model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_violin()
```



